#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/shell_env.sh"

DEFAULT_PROMPT_FILE="${SCRIPT_DIR}/hpsv2_subset.txt"
if [[ -f "${DEFAULT_PROMPT_FILE}" ]]; then
  PROMPT_FILE="${PROMPT_FILE:-${DEFAULT_PROMPT_FILE}}"
fi

OUT_ROOT="${OUT_ROOT:-${SCRIPT_DIR}/flux_bon_mcts_local_out}"
NUM_GPUS="${NUM_GPUS:-1}"
START_INDEX="${START_INDEX:-0}"
END_INDEX="${END_INDEX:-9}"

METHODS="${METHODS:-baseline bon_mcts}"
REWARD_BACKEND="${REWARD_BACKEND:-imagereward}"
REWARD_DEVICE="${REWARD_DEVICE:-cuda}"
EVAL_BEST_IMAGES="${EVAL_BEST_IMAGES:-1}"
EVAL_BACKENDS="${EVAL_BACKENDS:-imagereward hpsv2 pickscore unifiedreward}"
EVAL_REWARD_DEVICE="${EVAL_REWARD_DEVICE:-cuda}"
EVAL_ALLOW_MISSING_BACKENDS="${EVAL_ALLOW_MISSING_BACKENDS:-0}"

FLUX_BACKEND="${FLUX_BACKEND:-flux}"
CFG_SCALES="${CFG_SCALES:-1.0 1.25 1.5 1.75 2.0 2.25 2.5}"
BASELINE_GUIDANCE_SCALE="${BASELINE_GUIDANCE_SCALE:-1.0}"
STEPS="${STEPS:-4}"
N_VARIANTS="${N_VARIANTS:-3}"
N_SIMS="${N_SIMS:-24}"
UCB_C="${UCB_C:-1.41}"
SEED="${SEED:-42}"

BON_MCTS_N_SEEDS="${BON_MCTS_N_SEEDS:-5}"
BON_MCTS_TOPK="${BON_MCTS_TOPK:-1}"
BON_MCTS_SEED_STRIDE="${BON_MCTS_SEED_STRIDE:-1}"
BON_MCTS_SEED_OFFSET="${BON_MCTS_SEED_OFFSET:-0}"
BON_MCTS_SIM_ALLOC="${BON_MCTS_SIM_ALLOC:-split}"
BON_MCTS_MIN_SIMS="${BON_MCTS_MIN_SIMS:-4}"
BON_MCTS_PRESCREEN_GUIDANCE="${BON_MCTS_PRESCREEN_GUIDANCE:-}"

export PROMPT_FILE OUT_ROOT NUM_GPUS START_INDEX END_INDEX
export METHODS REWARD_BACKEND REWARD_DEVICE
export EVAL_BEST_IMAGES EVAL_BACKENDS EVAL_REWARD_DEVICE EVAL_ALLOW_MISSING_BACKENDS
export FLUX_BACKEND CFG_SCALES BASELINE_GUIDANCE_SCALE STEPS N_VARIANTS N_SIMS UCB_C SEED
export BON_MCTS_N_SEEDS BON_MCTS_TOPK BON_MCTS_SEED_STRIDE BON_MCTS_SEED_OFFSET BON_MCTS_SIM_ALLOC BON_MCTS_MIN_SIMS BON_MCTS_PRESCREEN_GUIDANCE

echo "[flux-bon-mcts-local]"
echo "  prompt_file=${PROMPT_FILE:-<unset>}"
echo "  out_root=${OUT_ROOT}"
echo "  methods=${METHODS}"
echo "  eval_backends=${EVAL_BACKENDS}"
echo "  bon_mcts: n_seeds=${BON_MCTS_N_SEEDS} topk=${BON_MCTS_TOPK} sim_alloc=${BON_MCTS_SIM_ALLOC}"

bash "${SCRIPT_DIR}/hpsv2_flux_schnell_ddp_suite.sh" "$@"
